/**
 * AUTO-GENERATED by ``scripts/seed_mock_data.py`` (molci ingest).
 * Do not edit by hand — re-run the seeder.
 */

export type IndexEntry = {
  snapshot_id: string;
  path: string;
  record: string;
  generation: number;
  profile: string;
  repository: string;
  commit: string;
  ref: string;
  workflow_run: number | null;
  producer: string;
  timestamp: string | null;
  [key: string]: unknown;
};

export type MockFixtures = {
  indexes: string[];
  entries: Record<string, IndexEntry[]>;
  snapshots: Record<string, unknown>;
};

export const fixtures: MockFixtures = {
  "entries": {
    "molcrafts-molrec/coverage": [
      {
        "commit": "0718293a4b5c6d7e8f90123456789012",
        "generation": 1,
        "path": "snapshots/molcrafts-molrec/coverage/1/coverage-default-0718293a4b5c.json",
        "producer": "coverage.py",
        "profile": "default",
        "record": "coverage",
        "ref": "refs/heads/main",
        "repository": "MolCrafts/molcrafts-molrec",
        "snapshot_id": "coverage-default-0718293a4b5c",
        "timestamp": "2026-09-20T11:08:00Z",
        "workflow_run": 92
      }
    ],
    "molcrafts-molrec/molrec": [
      {
        "commit": "0718293a4b5c6d7e8f90123456789012",
        "generation": 1,
        "path": "snapshots/molcrafts-molrec/molrec/1/molrec-default-0718293a4b5c.json",
        "producer": "molrec",
        "profile": "default",
        "record": "molrec",
        "ref": "refs/heads/main",
        "repository": "MolCrafts/molcrafts-molrec",
        "snapshot_id": "molrec-default-0718293a4b5c",
        "timestamp": "2026-09-20T11:10:00Z",
        "workflow_run": 92
      }
    ],
    "molcrafts-molrec/tests": [
      {
        "commit": "0718293a4b5c6d7e8f90123456789012",
        "generation": 1,
        "path": "snapshots/molcrafts-molrec/tests/1/tests-default-0718293a4b5c.json",
        "producer": "pytest",
        "profile": "default",
        "record": "tests",
        "ref": "refs/heads/main",
        "repository": "MolCrafts/molcrafts-molrec",
        "snapshot_id": "tests-default-0718293a4b5c",
        "timestamp": "2026-09-20T11:05:00Z",
        "workflow_run": 92
      }
    ],
    "molpy/benchmark": [
      {
        "commit": "c3d4e5f60718293a4b5c6d7e8f901234",
        "generation": 1,
        "path": "snapshots/molpy/benchmark/1/benchmark-linux-x86_64-c3d4e5f60718.json",
        "producer": "pytest-benchmark",
        "profile": "linux-x86_64",
        "record": "benchmark",
        "ref": "refs/heads/main",
        "repository": "MolCrafts/molpy",
        "snapshot_id": "benchmark-linux-x86_64-c3d4e5f60718",
        "timestamp": "2026-09-20T08:12:00Z",
        "workflow_run": 1215
      }
    ],
    "molpy/coverage": [
      {
        "commit": "c3d4e5f60718293a4b5c6d7e8f901234",
        "generation": 1,
        "path": "snapshots/molpy/coverage/1/coverage-linux-x86_64-c3d4e5f60718.json",
        "producer": "coverage.py",
        "profile": "linux-x86_64",
        "record": "coverage",
        "ref": "refs/heads/main",
        "repository": "MolCrafts/molpy",
        "snapshot_id": "coverage-linux-x86_64-c3d4e5f60718",
        "timestamp": "2026-09-20T08:22:00Z",
        "workflow_run": 1215
      }
    ],
    "molpy/regression": [
      {
        "commit": "c3d4e5f60718293a4b5c6d7e8f901234",
        "generation": 1,
        "path": "snapshots/molpy/regression/1/regression-linux-x86_64-c3d4e5f60718.json",
        "producer": "molpy-numerical",
        "profile": "linux-x86_64",
        "record": "regression",
        "ref": "refs/heads/main",
        "repository": "MolCrafts/molpy",
        "snapshot_id": "regression-linux-x86_64-c3d4e5f60718",
        "timestamp": "2026-09-20T08:18:00Z",
        "workflow_run": 1215
      }
    ],
    "molpy/tests": [
      {
        "commit": "a1b2c3d4e5f6789012345678abcdef01",
        "generation": 1,
        "path": "snapshots/molpy/tests/1/tests-linux-x86_64-a1b2c3d4e5f6.json",
        "producer": "pytest",
        "profile": "linux-x86_64",
        "record": "tests",
        "ref": "refs/heads/main",
        "repository": "MolCrafts/molpy",
        "snapshot_id": "tests-linux-x86_64-a1b2c3d4e5f6",
        "timestamp": "2026-09-18T09:12:00Z",
        "workflow_run": 1201
      },
      {
        "commit": "c3d4e5f60718293a4b5c6d7e8f901234",
        "generation": 1,
        "path": "snapshots/molpy/tests/1/tests-linux-x86_64-c3d4e5f60718.json",
        "producer": "pytest",
        "profile": "linux-x86_64",
        "record": "tests",
        "ref": "refs/heads/main",
        "repository": "MolCrafts/molpy",
        "snapshot_id": "tests-linux-x86_64-c3d4e5f60718",
        "timestamp": "2026-09-20T08:05:00Z",
        "workflow_run": 1215
      }
    ],
    "molrs/benchmark": [
      {
        "commit": "e5f60718293a4b5c6d7e8f9012345678",
        "generation": 1,
        "path": "snapshots/molrs/benchmark/1/benchmark-linux-x86_64-e5f60718293a.json",
        "producer": "criterion",
        "profile": "linux-x86_64",
        "record": "benchmark",
        "ref": "refs/heads/main",
        "repository": "MolCrafts/molrs",
        "snapshot_id": "benchmark-linux-x86_64-e5f60718293a",
        "timestamp": "2026-09-20T10:30:00Z",
        "workflow_run": 448
      },
      {
        "commit": "e5f60718293a4b5c6d7e8f9012345678",
        "generation": 1,
        "path": "snapshots/molrs/benchmark/1/benchmark-macos-aarch64-e5f60718293a.json",
        "producer": "criterion",
        "profile": "macos-aarch64",
        "record": "benchmark",
        "ref": "refs/heads/main",
        "repository": "MolCrafts/molrs",
        "snapshot_id": "benchmark-macos-aarch64-e5f60718293a",
        "timestamp": "2026-09-20T10:35:00Z",
        "workflow_run": 449
      }
    ],
    "molrs/coverage": [
      {
        "commit": "e5f60718293a4b5c6d7e8f9012345678",
        "generation": 1,
        "path": "snapshots/molrs/coverage/1/coverage-linux-x86_64-e5f60718293a.json",
        "producer": "llvm-cov",
        "profile": "linux-x86_64",
        "record": "coverage",
        "ref": "refs/heads/main",
        "repository": "MolCrafts/molrs",
        "snapshot_id": "coverage-linux-x86_64-e5f60718293a",
        "timestamp": "2026-09-20T10:40:00Z",
        "workflow_run": 448
      }
    ],
    "molrs/tests": [
      {
        "commit": "e5f60718293a4b5c6d7e8f9012345678",
        "generation": 1,
        "path": "snapshots/molrs/tests/1/tests-linux-x86_64-e5f60718293a.json",
        "producer": "cargo-nextest",
        "profile": "linux-x86_64",
        "record": "tests",
        "ref": "refs/heads/main",
        "repository": "MolCrafts/molrs",
        "snapshot_id": "tests-linux-x86_64-e5f60718293a",
        "timestamp": "2026-09-20T10:22:00Z",
        "workflow_run": 448
      }
    ]
  },
  "indexes": [
    "data/index/molcrafts-molrec/coverage.jsonl",
    "data/index/molcrafts-molrec/molrec.jsonl",
    "data/index/molcrafts-molrec/tests.jsonl",
    "data/index/molpy/benchmark.jsonl",
    "data/index/molpy/coverage.jsonl",
    "data/index/molpy/regression.jsonl",
    "data/index/molpy/tests.jsonl",
    "data/index/molrs/benchmark.jsonl",
    "data/index/molrs/coverage.jsonl",
    "data/index/molrs/tests.jsonl"
  ],
  "snapshots": {
    "snapshots/molcrafts-molrec/coverage/1/coverage-default-0718293a4b5c.json": {
      "manifest": {
        "producer": "coverage.py",
        "profile": "default",
        "provenance": {},
        "record": "coverage",
        "schema_version": "1",
        "source": {
          "commit": "0718293a4b5c6d7e8f90123456789012",
          "producer_version": null,
          "ref": "refs/heads/main",
          "repository": "MolCrafts/molcrafts-molrec",
          "run_attempt": null,
          "timestamp": "2026-09-20T11:08:00Z",
          "workflow_run": 92
        },
        "tracking": {
          "enabled": true,
          "generation": 1
        }
      },
      "payload": {
        "files": [
          {
            "lines": 97.0,
            "path": "src/molrec/schema.py",
            "uncovered": [
              210
            ]
          },
          {
            "lines": 78.5,
            "path": "src/molrec/bench.py",
            "uncovered": [
              44,
              45,
              67,
              68
            ]
          }
        ],
        "totals": {
          "branches": 84.0,
          "functions": 96.2,
          "lines": 91.5,
          "statements": 90.8
        }
      }
    },
    "snapshots/molcrafts-molrec/molrec/1/molrec-default-0718293a4b5c.json": {
      "manifest": {
        "producer": "molrec",
        "profile": "default",
        "provenance": {},
        "record": "molrec",
        "schema_version": "1",
        "source": {
          "commit": "0718293a4b5c6d7e8f90123456789012",
          "producer_version": null,
          "ref": "refs/heads/main",
          "repository": "MolCrafts/molcrafts-molrec",
          "run_attempt": null,
          "timestamp": "2026-09-20T11:10:00Z",
          "workflow_run": 92
        },
        "tracking": {
          "enabled": true,
          "generation": 1
        }
      },
      "payload": {
        "schema_version": "0.1.0"
      }
    },
    "snapshots/molcrafts-molrec/tests/1/tests-default-0718293a4b5c.json": {
      "manifest": {
        "producer": "pytest",
        "profile": "default",
        "provenance": {},
        "record": "tests",
        "schema_version": "1",
        "source": {
          "commit": "0718293a4b5c6d7e8f90123456789012",
          "producer_version": null,
          "ref": "refs/heads/main",
          "repository": "MolCrafts/molcrafts-molrec",
          "run_attempt": null,
          "timestamp": "2026-09-20T11:05:00Z",
          "workflow_run": 92
        },
        "tracking": {
          "enabled": true,
          "generation": 1
        }
      },
      "payload": {
        "failed": 0,
        "passed": 86
      }
    },
    "snapshots/molpy/benchmark/1/benchmark-linux-x86_64-c3d4e5f60718.json": {
      "manifest": {
        "producer": "pytest-benchmark",
        "profile": "linux-x86_64",
        "provenance": {},
        "record": "benchmark",
        "schema_version": "1",
        "source": {
          "commit": "c3d4e5f60718293a4b5c6d7e8f901234",
          "producer_version": null,
          "ref": "refs/heads/main",
          "repository": "MolCrafts/molpy",
          "run_attempt": null,
          "timestamp": "2026-09-20T08:12:00Z",
          "workflow_run": 1215
        },
        "tracking": {
          "enabled": true,
          "generation": 1
        }
      },
      "payload": {
        "metrics": {
          "mean_ns": 12.5
        }
      }
    },
    "snapshots/molpy/coverage/1/coverage-linux-x86_64-c3d4e5f60718.json": {
      "manifest": {
        "producer": "coverage.py",
        "profile": "linux-x86_64",
        "provenance": {},
        "record": "coverage",
        "schema_version": "1",
        "source": {
          "commit": "c3d4e5f60718293a4b5c6d7e8f901234",
          "producer_version": null,
          "ref": "refs/heads/main",
          "repository": "MolCrafts/molpy",
          "run_attempt": null,
          "timestamp": "2026-09-20T08:22:00Z",
          "workflow_run": 1215
        },
        "tracking": {
          "enabled": true,
          "generation": 1
        }
      },
      "payload": {
        "files": [
          {
            "lines": 90.1,
            "path": "molpy/core/frame.py",
            "uncovered": [
              55,
              56
            ]
          },
          {
            "lines": 74.0,
            "path": "molpy/io/xyz.py",
            "uncovered": [
              12,
              13,
              40
            ]
          }
        ],
        "totals": {
          "branches": 68.9,
          "functions": 88.0,
          "lines": 82.3,
          "statements": 81.5
        }
      }
    },
    "snapshots/molpy/regression/1/regression-linux-x86_64-c3d4e5f60718.json": {
      "manifest": {
        "producer": "molpy-numerical",
        "profile": "linux-x86_64",
        "provenance": {},
        "record": "regression",
        "schema_version": "1",
        "source": {
          "commit": "c3d4e5f60718293a4b5c6d7e8f901234",
          "producer_version": null,
          "ref": "refs/heads/main",
          "repository": "MolCrafts/molpy",
          "run_attempt": null,
          "timestamp": "2026-09-20T08:18:00Z",
          "workflow_run": 1215
        },
        "tracking": {
          "enabled": true,
          "generation": 1
        }
      },
      "payload": {
        "max_abs_error": 1.2e-08
      }
    },
    "snapshots/molpy/tests/1/tests-linux-x86_64-a1b2c3d4e5f6.json": {
      "manifest": {
        "producer": "pytest",
        "profile": "linux-x86_64",
        "provenance": {},
        "record": "tests",
        "schema_version": "1",
        "source": {
          "commit": "a1b2c3d4e5f6789012345678abcdef01",
          "producer_version": null,
          "ref": "refs/heads/main",
          "repository": "MolCrafts/molpy",
          "run_attempt": null,
          "timestamp": "2026-09-18T09:12:00Z",
          "workflow_run": 1201
        },
        "tracking": {
          "enabled": true,
          "generation": 1
        }
      },
      "payload": {
        "failed": 0,
        "passed": 412
      }
    },
    "snapshots/molpy/tests/1/tests-linux-x86_64-c3d4e5f60718.json": {
      "manifest": {
        "producer": "pytest",
        "profile": "linux-x86_64",
        "provenance": {},
        "record": "tests",
        "schema_version": "1",
        "source": {
          "commit": "c3d4e5f60718293a4b5c6d7e8f901234",
          "producer_version": null,
          "ref": "refs/heads/main",
          "repository": "MolCrafts/molpy",
          "run_attempt": null,
          "timestamp": "2026-09-20T08:05:00Z",
          "workflow_run": 1215
        },
        "tracking": {
          "enabled": true,
          "generation": 1
        }
      },
      "payload": {
        "failed": 0,
        "passed": 418
      }
    },
    "snapshots/molrs/benchmark/1/benchmark-linux-x86_64-e5f60718293a.json": {
      "manifest": {
        "producer": "criterion",
        "profile": "linux-x86_64",
        "provenance": {},
        "record": "benchmark",
        "schema_version": "1",
        "source": {
          "commit": "e5f60718293a4b5c6d7e8f9012345678",
          "producer_version": null,
          "ref": "refs/heads/main",
          "repository": "MolCrafts/molrs",
          "run_attempt": null,
          "timestamp": "2026-09-20T10:30:00Z",
          "workflow_run": 448
        },
        "tracking": {
          "enabled": true,
          "generation": 1
        }
      },
      "payload": {
        "suite": "neighbor_list"
      }
    },
    "snapshots/molrs/benchmark/1/benchmark-macos-aarch64-e5f60718293a.json": {
      "manifest": {
        "producer": "criterion",
        "profile": "macos-aarch64",
        "provenance": {},
        "record": "benchmark",
        "schema_version": "1",
        "source": {
          "commit": "e5f60718293a4b5c6d7e8f9012345678",
          "producer_version": null,
          "ref": "refs/heads/main",
          "repository": "MolCrafts/molrs",
          "run_attempt": null,
          "timestamp": "2026-09-20T10:35:00Z",
          "workflow_run": 449
        },
        "tracking": {
          "enabled": true,
          "generation": 1
        }
      },
      "payload": {
        "suite": "neighbor_list"
      }
    },
    "snapshots/molrs/coverage/1/coverage-linux-x86_64-e5f60718293a.json": {
      "manifest": {
        "producer": "llvm-cov",
        "profile": "linux-x86_64",
        "provenance": {},
        "record": "coverage",
        "schema_version": "1",
        "source": {
          "commit": "e5f60718293a4b5c6d7e8f9012345678",
          "producer_version": null,
          "ref": "refs/heads/main",
          "repository": "MolCrafts/molrs",
          "run_attempt": null,
          "timestamp": "2026-09-20T10:40:00Z",
          "workflow_run": 448
        },
        "tracking": {
          "enabled": true,
          "generation": 1
        }
      },
      "payload": {
        "files": [
          {
            "lines": 94.2,
            "path": "molrs/src/spatial/neighbors.rs",
            "uncovered": [
              412,
              418
            ]
          },
          {
            "lines": 81.0,
            "path": "molrs/src/md/lj.rs",
            "uncovered": [
              88,
              91,
              120
            ]
          }
        ],
        "totals": {
          "branches": 71.2,
          "functions": 93.0,
          "lines": 88.4,
          "statements": 87.1
        }
      }
    },
    "snapshots/molrs/tests/1/tests-linux-x86_64-e5f60718293a.json": {
      "manifest": {
        "producer": "cargo-nextest",
        "profile": "linux-x86_64",
        "provenance": {},
        "record": "tests",
        "schema_version": "1",
        "source": {
          "commit": "e5f60718293a4b5c6d7e8f9012345678",
          "producer_version": null,
          "ref": "refs/heads/main",
          "repository": "MolCrafts/molrs",
          "run_attempt": null,
          "timestamp": "2026-09-20T10:22:00Z",
          "workflow_run": 448
        },
        "tracking": {
          "enabled": true,
          "generation": 1
        }
      },
      "payload": {
        "failed": 0,
        "passed": 1601
      }
    }
  }
} as const;
