"""Seed Git-friendly mock index data using ``import molci as mci``.

Writes tracked snapshots under ``data/`` so prepare-data / publish see the same
shapes production ingest produces. Also refreshes ``site/mock/fixtures.ts``
consumed by ``rspack-plugin-mock`` during ``npm run dev``.

Safe to re-run: clears mock projects first.
"""

from __future__ import annotations

import json
import shutil
from pathlib import Path

import molci as mci

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data"
FIXTURES_TS = ROOT / "site" / "mock" / "fixtures.ts"

MOCK_PROJECTS = ("molpy", "molrs", "molcrafts-molrec")


def _clear_mock_trees() -> None:
    for name in MOCK_PROJECTS:
        for base in (DATA / "snapshots" / name, DATA / "index" / name):
            if base.exists():
                shutil.rmtree(base)


def _entry(
    *,
    kind: str,
    project_repo: str,
    commit: str,
    profile: str,
    producer: str,
    timestamp: str,
    workflow_run: int,
    payload: dict,
) -> mci.Snapshot:
    return mci.Snapshot(
        manifest=mci.Manifest(
            kind=kind,
            source=mci.Source(
                repository=project_repo,
                commit=commit,
                ref="refs/heads/main",
                workflow_run=workflow_run,
                timestamp=timestamp,
            ),
            producer=producer,
            profile=profile,
            tracking=mci.Tracking(enabled=True, generation=1),
        ),
        payload=payload,
    )


def _export_fixtures() -> None:
    """Rebuild TypeScript fixtures from the JSONL index + snapshot files molci wrote."""
    index_root = DATA / "index"
    indexes: list[str] = []
    entries: dict[str, list[dict]] = {}
    if index_root.exists():
        for path in sorted(index_root.rglob("*.jsonl")):
            rel = path.relative_to(DATA).as_posix()
            indexes.append(f"data/{rel}")
            project = path.parent.name
            kind = path.stem
            key = f"{project}/{kind}"
            rows: list[dict] = []
            for line in path.read_text(encoding="utf-8").splitlines():
                line = line.strip()
                if line:
                    rows.append(json.loads(line))
            entries[key] = rows

    snapshots: dict[str, dict] = {}
    snap_root = DATA / "snapshots"
    if snap_root.exists():
        for path in sorted(snap_root.rglob("*.json")):
            rel = path.relative_to(DATA).as_posix()
            snapshots[rel] = json.loads(path.read_text(encoding="utf-8"))

    payload = {"indexes": indexes, "entries": entries, "snapshots": snapshots}
    body = json.dumps(payload, indent=2, ensure_ascii=False, sort_keys=True)
    FIXTURES_TS.write_text(
        "/**\n"
        " * AUTO-GENERATED by ``scripts/seed_mock_data.py`` (molci ingest).\n"
        " * Do not edit by hand — re-run the seeder.\n"
        " */\n\n"
        "export type IndexEntry = {\n"
        "  snapshot_id: string;\n"
        "  path: string;\n"
        "  kind: string;\n"
        "  generation: number;\n"
        "  profile: string;\n"
        "  repository: string;\n"
        "  commit: string;\n"
        "  ref: string;\n"
        "  workflow_run: number | null;\n"
        "  producer: string;\n"
        "  timestamp: string | null;\n"
        "  [key: string]: unknown;\n"
        "};\n\n"
        "export type MockFixtures = {\n"
        "  indexes: string[];\n"
        "  entries: Record<string, IndexEntry[]>;\n"
        "  snapshots: Record<string, unknown>;\n"
        "};\n\n"
        f"export const fixtures: MockFixtures = {body} as const;\n",
        encoding="utf-8",
    )


def main() -> None:
    DATA.mkdir(parents=True, exist_ok=True)
    _clear_mock_trees()

    seeds: list[tuple[str, mci.Snapshot]] = [
        (
            "molpy",
            _entry(
                kind="tests",
                project_repo="MolCrafts/molpy",
                commit="a1b2c3d4e5f6789012345678abcdef01",
                profile="linux-x86_64",
                producer="pytest",
                timestamp="2026-09-18T09:12:00Z",
                workflow_run=1201,
                payload={"passed": 412, "failed": 0},
            ),
        ),
        (
            "molpy",
            _entry(
                kind="tests",
                project_repo="MolCrafts/molpy",
                commit="c3d4e5f60718293a4b5c6d7e8f901234",
                profile="linux-x86_64",
                producer="pytest",
                timestamp="2026-09-20T08:05:00Z",
                workflow_run=1215,
                payload={"passed": 418, "failed": 0},
            ),
        ),
        (
            "molpy",
            _entry(
                kind="benchmark",
                project_repo="MolCrafts/molpy",
                commit="c3d4e5f60718293a4b5c6d7e8f901234",
                profile="linux-x86_64",
                producer="pytest-benchmark",
                timestamp="2026-09-20T08:12:00Z",
                workflow_run=1215,
                payload={"metrics": {"mean_ns": 12.5}},
            ),
        ),
        (
            "molpy",
            _entry(
                kind="regression",
                project_repo="MolCrafts/molpy",
                commit="c3d4e5f60718293a4b5c6d7e8f901234",
                profile="linux-x86_64",
                producer="molpy-numerical",
                timestamp="2026-09-20T08:18:00Z",
                workflow_run=1215,
                payload={"max_abs_error": 1.2e-8},
            ),
        ),
        (
            "molrs",
            _entry(
                kind="tests",
                project_repo="MolCrafts/molrs",
                commit="e5f60718293a4b5c6d7e8f9012345678",
                profile="linux-x86_64",
                producer="cargo-nextest",
                timestamp="2026-09-20T10:22:00Z",
                workflow_run=448,
                payload={"passed": 1601, "failed": 0},
            ),
        ),
        (
            "molrs",
            _entry(
                kind="benchmark",
                project_repo="MolCrafts/molrs",
                commit="e5f60718293a4b5c6d7e8f9012345678",
                profile="linux-x86_64",
                producer="criterion",
                timestamp="2026-09-20T10:30:00Z",
                workflow_run=448,
                payload={"suite": "neighbor_list"},
            ),
        ),
        (
            "molrs",
            _entry(
                kind="benchmark",
                project_repo="MolCrafts/molrs",
                commit="e5f60718293a4b5c6d7e8f9012345678",
                profile="macos-aarch64",
                producer="criterion",
                timestamp="2026-09-20T10:35:00Z",
                workflow_run=449,
                payload={"suite": "neighbor_list"},
            ),
        ),
        (
            "molrs",
            _entry(
                kind="coverage",
                project_repo="MolCrafts/molrs",
                commit="e5f60718293a4b5c6d7e8f9012345678",
                profile="linux-x86_64",
                producer="llvm-cov",
                timestamp="2026-09-20T10:40:00Z",
                workflow_run=448,
                payload={
                    "totals": {
                        "lines": 88.4,
                        "branches": 71.2,
                        "functions": 93.0,
                        "statements": 87.1,
                    },
                    "files": [
                        {
                            "path": "molrs/src/spatial/neighbors.rs",
                            "lines": 94.2,
                            "uncovered": [412, 418],
                        },
                        {
                            "path": "molrs/src/md/lj.rs",
                            "lines": 81.0,
                            "uncovered": [88, 91, 120],
                        },
                    ],
                },
            ),
        ),
        (
            "molcrafts-molrec",
            _entry(
                kind="tests",
                project_repo="MolCrafts/molcrafts-molrec",
                commit="0718293a4b5c6d7e8f90123456789012",
                profile="default",
                producer="pytest",
                timestamp="2026-09-20T11:05:00Z",
                workflow_run=92,
                payload={"passed": 86, "failed": 0},
            ),
        ),
        (
            "molcrafts-molrec",
            _entry(
                kind="coverage",
                project_repo="MolCrafts/molcrafts-molrec",
                commit="0718293a4b5c6d7e8f90123456789012",
                profile="default",
                producer="coverage.py",
                timestamp="2026-09-20T11:08:00Z",
                workflow_run=92,
                payload={
                    "totals": {
                        "lines": 91.5,
                        "branches": 84.0,
                        "functions": 96.2,
                        "statements": 90.8,
                    },
                    "files": [
                        {
                            "path": "src/molrec/schema.py",
                            "lines": 97.0,
                            "uncovered": [210],
                        },
                        {
                            "path": "src/molrec/bench.py",
                            "lines": 78.5,
                            "uncovered": [44, 45, 67, 68],
                        },
                    ],
                },
            ),
        ),
        (
            "molpy",
            _entry(
                kind="coverage",
                project_repo="MolCrafts/molpy",
                commit="c3d4e5f60718293a4b5c6d7e8f901234",
                profile="linux-x86_64",
                producer="coverage.py",
                timestamp="2026-09-20T08:22:00Z",
                workflow_run=1215,
                payload={
                    "totals": {
                        "lines": 82.3,
                        "branches": 68.9,
                        "functions": 88.0,
                        "statements": 81.5,
                    },
                    "files": [
                        {
                            "path": "molpy/core/frame.py",
                            "lines": 90.1,
                            "uncovered": [55, 56],
                        },
                        {
                            "path": "molpy/io/xyz.py",
                            "lines": 74.0,
                            "uncovered": [12, 13, 40],
                        },
                    ],
                },
            ),
        ),
        (
            "molcrafts-molrec",
            _entry(
                kind="molrec",
                project_repo="MolCrafts/molcrafts-molrec",
                commit="0718293a4b5c6d7e8f90123456789012",
                profile="default",
                producer="molrec",
                timestamp="2026-09-20T11:10:00Z",
                workflow_run=92,
                payload={"schema_version": "0.1.0"},
            ),
        ),
    ]

    for project, snap in seeds:
        mci.ingest_snapshot(DATA, project, snap)

    _export_fixtures()
    print(f"seeded {len(seeds)} snapshots under {DATA}")
    print(f"wrote {FIXTURES_TS.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
